config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
    @members = ['claire', 'toni', 'santi', 'sarah', 'olivia']

    search = params[:member]

    @members = @members.select do |member|
      if search
        member.start_with? search.downcase
      end
    end
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsIntro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <h1>The Spoon</h1>
  <p>Testing somethings</p>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>
<p>Relearning Rails</p>

app/views/pages/contact.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Contact</title>
</head>
<body>
<h1>Contact Page</h1>

<ol>
  <% @members.each do |member|  %>
  <li><%= member.capitalize %></li>
  <% end %>
</ol>

<form action="/contact" method="get">
  <label for="member">Please Type a name...</label>
  <input type="text" name ="member" id="member" value = <%=params[:member]%>>
  <input type="submit">
</form>

<%= link_to("Home", root_path) %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Welcome Home</h1>

<%  %>
<%= Time.now %>
<%= link_to("Contact Us", contact_path) %>